cq4ds:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'data/database.duckdb'
  target: dev_with_fal
  outputs:
    dev_with_fal:
      type: fal
      db_profile: duckdb
    duckdb:
        type: duckdb
        path: 'data/database.duckdb'
