## Python CircleCI 2.0 configuration file
##
## Check https://circleci.com/docs/2.0/language-python/ for more details
##

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    steps:
      - checkout
      - run:
          name: install hamilton dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            python --version
            pip --version
            pip install -r requirements-test.txt
            pip install -r requirements.txt
        # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py pytest

      # run coverage tool!
      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            python -m pytest --cov=hamilton tests/

  build-py37:
    docker:
      - image: circleci/python:3.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    steps:
      - checkout
      - run:
          name: install hamilton dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            python --version
            pip --version
            pip install -r requirements-test.txt
            pip install -r requirements.txt

      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python setup.py pytest

      # run coverage tool!
      - run:
          name: run coverage
          command: |
            . venv/bin/activate
            python -m pytest --cov=hamilton tests/
  pre-commit:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run pre-commit hooks
          command: |
            pip install pre-commit
            pre-commit run --all-files
workflow:
  version: 2

  unit-test-workflow:
    - build
    - build-py37
    - pre-commit
