version: 2.1
jobs:
  test:
    parameters:
      python-version:
        type: string
      task:
        type: string
    docker:
      - image: circleci/python:<< parameters.python-version >>
    environment:
      TASK: << parameters.task >>
    steps:
      - checkout
      - run:
          name: install dependencies
          command: .ci/setup.sh
      - run:
          name: run tests
          command: .ci/test.sh
workflows:
  unit-test-workflow:
    jobs:
      - test:
          name: build-py36
          python-version: '3.6'
          task: tests
      - test:
          name: build-py37
          python-version: '3.7'
          task: tests
      - test:
          name: build-py38
          python-version: '3.8'
          task: tests
      - test:
          name: build-py39
          python-version: '3.9'
          task: tests
      - test:
          name: pre-commit
          python-version: '3.9'
          task: pre-commit
      - test:
          name: dask-py36
          python-version: '3.6'
          task: dask
      - test:
          name: dask-py37
          python-version: '3.7'
          task: dask
      - test:
          name: ray-py37
          python-version: '3.7'
          task: ray
      - test:
          name: spark-py38
          python-version: '3.8'
          task: pyspark
      - test:
          name: integrations-py36
          python-version: '3.6'
          task: integrations
      - test:
          name: integrations-py37
          python-version: '3.7'
          task: integrations
      - test:
          name: integrations-py38
          python-version: '3.8'
          task: integrations
      - test:
          name: integrations-py39
          python-version: '3.9'
          task: integrations
      - test:
          name: asyncio-py39
          python-version: '3.9'
          task: asyncio
