blank_issues_enabled: true
contact_links:
  - name: Stitch Fix Hamilton Open Source Discord Server
    url: https://discord.gg/wCqxqBqn73
    about: We are piloting using discord for chat. Feel free to try asking questions there first.
