blank_issues_enabled: true
contact_links:
  - name: Stitch Fix Open Source Discord Channel
    url: https://discord.gg/wCqxqBqn73
    about: We are piloting using discord for chat. Feel free to try asking questions there first.
